### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by mihaicris-adoreme** [talkable/ios-sdk#13]
We are migrating from Cocoapods. We would like to use Swift Package Manager for Talkable integration.

**Comment by dgtv** [comment]
Hi @mihaicris-adoreme, thanks for your point. Currently Talkable iOS SDK is not supporting Swift, so the only options for now is Cocoapods or static library. But we do have plans to rewrite the SDK with Swift support sometime in the future.

**Comment by mihaicris-adoreme** [comment]
Hi @dgtv,

Could you consider distributing the Talkable binary framework as a Swift package?

[Distributing Binary Frameworks as Swift Packages](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages)

Later edit: Consider supporting M1 arm64-simulator as well.

Thanks!

**Comment by dgtv** [comment]
@mihaicris-adoreme "Swift support in the SDK" mentioned before includes Swift package distribution too. We'll review a possibility to add this to our recent sprints and I'll respond to you about the result. Thanks

**Comment by mihaicris-adoreme** [comment]
Hi, 

Any update on this issue?

Thank you

**Comment by dgtv** [comment]
@mihaicris-adoreme Hi,
Sorry, no updates for now

**Comment by mihaicris-adoreme** [comment]
Hi, I am currently not able to build the project on M1 Apple machine for running in simulator due to Talkable libray not supporting arm simulator. 
May I kindly ask you to provide an updated library version ?
Thank you

**Comment by dgtv** [comment]
Hello,
We're working on it (arm simulator support). I'll notify you once it will be done

**Comment by dgtv** [comment]
@mihaicris-adoreme How did you installed Talkable SDK: with Cocoapods or a framework (static library)?

**Comment by mihaicris-adoreme** [comment]
Hi @dgtv,
We have migrated from Cocoapods. We are manually linking the `TalkableSDK.framework` to the app target.
I think having a FAT xcframework would be enough, however a SPM package wrapper with binary resource would be ideal, not to store the xcframework in the git repo.

**Comment by dgtv** [comment]
Thanks @mihaicris-adoreme.
The problem is that we currently don't ship Talkable SDK as a FAT xcframework, but as a FAT framework and don't support Swift yet.
As a quick solution I can build not FAT framework for arm64 simulator and provide it to you, so you'll be able to run your app with Talkable SDK on Apple Silicon emulator, but then you'll have to use another library for non emulator case.
We're currently working on moving from FAT framework to FAT xcframework, but this is still in progress.

**Comment by mihaicris-adoreme** [comment]
Hi @dgtv , 

I was able to create XCFramework with this script:

First you create a swift package in the repo 

`swift package init --type=library`
and edit the info of the library

Then you run this script in the git root folder

```bash
#!/bin/bash
set -e

WORKING_DIR=$(pwd)
FRAMEWORK_FOLDER_NAME="TEMP_BUILD"
FRAMEWORK_NAME="TalkableSDK"
FRAMEWORK_PATH="${WORKING_DIR}/${FRAMEWORK_NAME}.xcframework"
FRAMEWORK_ZIP_PATH="${WORKING_DIR}/${FRAMEWORK_NAME}.xcframework.zip"
BUILD_SCHEME="TalkableSDK"
SIMULATOR_ARCHIVE_PATH="${WORKING_DIR}/${FRAMEWORK_FOLDER_NAME}/simulator.xcarchive"
IOS_DEVICE_ARCHIVE_PATH="${WORKING_DIR}/${FRAMEWORK_FOLDER_NAME}/iOS.xcarchive"
CATALYST_ARCHIVE_PATH="${WORKING_DIR}/${FRAMEWORK_FOLDER_NAME}/catalyst.xcarchive"

rm -rf "${FRAMEWORK_FOLDER_NAME}"
rm -rf "${FRAMEWORK_PATH}"

mkdir "${FRAMEWORK_FOLDER_NAME}"

echo "Created ${FRAMEWORK_FOLDER_NAME}"
echo "Archiving ${FRAMEWORK_NAME}"

xcodebuild archive ONLY_ACTIVE_ARCH=NO \
    -scheme ${BUILD_SCHEME} \
    -destination="generic/platform=iOS Simulator" \
    -archivePath "${SIMULATOR_ARCHIVE_PATH}" \
    -sdk iphonesimulator SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -scheme ${BUILD_SCHEME} \
    -destination="generic/platform=iOS" \
    -archivePath "${IOS_DEVICE_ARCHIVE_PATH}" \
    -sdk iphoneos SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -scheme ${BUILD_SCHEME} \
    -destination='generic/platform=macOS,variant=Mac Catalyst' \
    -archivePath "${CATALYST_ARCHIVE_PATH}" SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild -create-xcframework \
    -framework ${SIMULATOR_ARCHIVE_PATH}/Products/Library/Frameworks/${FRAMEWORK_NAME}.framework \
    -framework ${IOS_DEVICE_ARCHIVE_PATH}/Products/Library/Frameworks/${FRAMEWORK_NAME}.framework \
    -framework ${CATALYST_ARCHIVE_PATH}/Products/Library/Frameworks/${FRAMEWORK_NAME}.framework \
    -output "${FRAMEWORK_PATH}"

rm -rf "${SIMULATOR_ARCHIVE_PATH}"
rm -rf "${IOS_DEVICE_ARCHIVE_PATH}"
rm -rf "${CATALYST_ARCHIVE_PATH}"
rm -rf "${FRAMEWORK_FOLDER_NAME}"

ditto -c -k --sequesterRsrc --keepParent ${FRAMEWORK_PATH} ${FRAMEWORK_ZIP_PATH}
echo $(swift package compute-checksum ${FRAMEWORK_ZIP_PATH})
open "${WORKING_DIR}"
```

If you run this script in the root git folder you get a FAT XCFramework.

You commit this zip file to the repo

and add to Package.swift a  binary target as described here https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

```swift
.binaryTarget(
            name: "SomeRemoteBinaryPackage",
            url: "https://url/to/some/remote/xcframework.zip",
            checksum: "The checksum of the ZIP archive that contains the XCFramework."
        ),
```

and make a new commit with the url of the zip file in the repo and checksum that is given by the script.

Give it a try!

**Comment by dgtv** [comment]
@mihaicris-adoreme Thanks so much for your support! It was very helpful.
I've updated our builder, so issue with arm64 simulator should gone. Now we're testing the newly built framework and will release the update once QA is done. You can track the progress here: https://github.com/talkable/ios-sdk/pull/14

About Swift Package manager, thanks for you guidelines, they will help us to add it faster once we have time for this. But we'll not add it in this release, as we should investigate issues about adding Swift support to the SDK we faced previous time when tried to do this, sorry.

**Comment by mihaicris-adoreme** [comment]
Great, thanks!

**Comment by dgtv** [comment]
Hello @mihaicris-adoreme,
We've released updated builder and updated SDK archive file inside Github ([Release 1.4.12](https://github.com/talkable/ios-sdk/releases/tag/1.4.12)) and at [docs.talkable.com](docs.talkable.com) ([Getting Started](https://docs.talkable.com/ios_sdk/getting_started.html), [SDK download link](https://talkable-downloads.s3.amazonaws.com/ios-sdk/talkable_ios_sdk.zip)). So issue with arm64 should gone. Also, Mac Catalyst build was added. Sorry for the inconvenience.
Keeping this issue opened till we introduce support of Swift Package manager.

**Comment by mihaicris-adoreme** [comment]
Thank you!
Question, was the framework tested infernally also on M1 by your QA team?

**Comment by dgtv** [comment]
@mihaicris-adoreme Yes, it was

**Comment by gcohen-dev** [comment]
Hey, 
Are there any updates regards the SPM package?

**Comment by dgtv** [comment]
Hey,
Unfortunately no updates regarding this for now, sorry.

**Comment by dgtv** [comment]
@mihaicris-adoreme @gcohen-dev Hi, we have great news for you! We took Swift Package Manager support into development and it will be available soon. Here is related pull: https://github.com/talkable/ios-sdk/pull/16.
I'll notify you once more after the release.

**Comment by mihaicris-adoreme** [comment]
@dgtv Thanks for solving this!

**Comment by mihaicris-adoreme** [comment]
Hi, I think you need to make a new tag version (e.g. 1.5.0) having the new Package.swift manifest file
<img width="715" alt="image" src="https://user-images.githubusercontent.com/68323356/179776225-e5dfdb6f-2055-4258-aac9-04f6a1ca77e1.png">

if works only if I use the master branch as package version.
Please test with a new Xcode project, 

Thanks!

**Comment by dgtv** [comment]
Hi @mihaicris-adoreme,
Thanks for the notice! The SDK was just in the process of release and QA and now it can be used with Swift Package Manager officially.
Here is actual documentation: https://docs.talkable.com/ios_sdk/getting_started.html
Thanks again for your support, we appreciate it!
