### ISSUE TITLE
"The code signature version is no longer supported." error upon device install using latest TalkableSDK.xcframework

### ISSUE THREAD

**Issue by ehyche** [talkable/ios-sdk#15]
I am integrating the latest `TalkableSDK.xcframework` into our build (1.4.12). When I build and run on simulator, it works fine. However, when I try to install to an iOS device, I get the following "code signature version is no longer supported" version. I am building using Xcode Version 13.4 (13F17a) on a M1 MacBook Pro running MacOS Monterey (macOS 12.4) and trying to install to an iPhone 11 running iOS 15.5.

Here is the error:

```
Unable to install "Coach"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    DVTErrorCreationDateKey = "2022-06-06 12:55:55 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
The code signature version is no longer supported.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE8008029)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011fda1614 DTDKCreateNSErrorFromAMDErrorCode + 272
	1   DTDeviceKitBase                     0x000000011fddadd8 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 160
	2   DVTFoundation                       0x00000001039e9be8 DVTInvokeWithStrongOwnership + 76
	3   DTDeviceKitBase                     0x000000011fddab30 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1336
	4   IDEiOSSupportCore                   0x000000011fcb9590 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.301 + 2916
        ...
```

This is blocking completely our usage of Talkable in our app.

**Comment by ehyche** [comment]
More on this. According to [this Apple documentation](https://developer.apple.com/documentation/xcode/using-the-latest-code-signature-format), I ran the `codesign` utility on the `ios-arm64_armv7` embedded framework:

```
$ cd TalkableSDK.xcframework
$ cd ios-arm64_armv7
$ codesign -dv TalkableSDK.framework
```

and I see the output:

```
Executable=/Users/ehyche/src/github/noom/coach-ios/Coach_iOS/lib/TalkableSDK.xcframework/ios-arm64_armv7/TalkableSDK.framework/TalkableSDK
Identifier=com.talkable.ios-sdk
Format=bundle with generic
CodeDirectory v=20200 size=212 flags=0x0(none) hashes=1+3 location=embedded
Signature size=4858
Signed Time=Jan 14, 2022 at 8:46:02 AM
Info.plist entries=21
TeamIdentifier=97R9ZGB9VS
Sealed Resources version=2 rules=10 files=6
Internal requirements count=1 size=180
```

Note the following line from above:

```
CodeDirectory v=20200 size=212 flags=0x0(none) hashes=1+3 location=embedded
```

According to Apple's documentation above:

> Look in the output for a string such as CodeDirectory v=20500. For any value of v less than 20400, you need to re-sign your app.

So this `TalkableSDK.xcframework` is unusable in Xcode 13 and above when trying to install on iOS 15+ devices.

**Comment by dgtv** [comment]
Hi @ehyche,
Thanks so much for the detailed explanation of the issue!
We're currently on it and will let you know once have updates.
Sorry for the inconvenience.

**Comment by dgtv** [comment]
@ehyche Looks like we found a way to resolve this: please change "Embed" setting to "Do Not Embed" for Talkable framework:
<img width="1438" alt="Screenshot 2022-06-07 at 11 38 03 PM" src="https://user-images.githubusercontent.com/8052706/172487596-279ed518-a0fc-4a0e-b560-57d4d2068f2c.png">
