### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by amarnik** [talkable/ios-sdk#5]
When submitting the app with TalkableSDK framework I am getting this warning from Apple:

ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Found this usage in your repo: https://github.com/talkable/ios-sdk/blob/413eacecba1814195a06f638602f41de356b567f/Talkable/Talkable.m#L827

**Comment by zhuravel** [comment]
Thanks @amarnik

@dgtv Please take a look
